import { CaretDown, PaperPlaneTilt, SlidersHorizontal } from "@phosphor-icons/react";
import type React from "react";
import { useState } from "react";
import { SettingsToggleCard } from "../settings/SettingsToggleCard";
import type { RoleChannelBinding, RoleFormState } from "../shared/types";
import { roleDeliveryFieldClass } from "./roleDeliveryStyles";
import { buildProactiveTransportSequence, roleBindingChannelLabel } from "./roleChannelBindings";

function parseNumber(value: string, fallback: number): number {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : fallback;
}

type RoleProactiveSettingsPanelProps = {
  bindings: RoleChannelBinding[];
  roleForm: RoleFormState;
  onUpdate: (next: React.SetStateAction<RoleFormState>) => void;
};

/** Configures the delivery policy after role channels have been selected. */
export function RoleProactiveSettingsPanel({ bindings, roleForm, onUpdate }: RoleProactiveSettingsPanelProps) {
  const [executionOpen, setExecutionOpen] = useState(false);
  const selectedBinding = bindings.find((binding) => binding.channel === roleForm.proactiveTargetChannel && binding.chat_id === roleForm.proactiveTargetChatId);
  const transportSequence = selectedBinding ? buildProactiveTransportSequence(bindings, roleForm.proactiveTargetChannel ?? "", roleForm.proactiveTargetChatId ?? "") : [];
  const usableBindings = bindings.filter((binding) => binding.chat_id.trim());
  const updateNumber = (field: "proactiveAgentMaxSteps" | "proactiveAgentContentLimit" | "proactiveAgentWebFetchMaxChars" | "proactiveDriftMaxSteps" | "proactiveDriftMinIntervalHours", fallback: number) => (event: React.ChangeEvent<HTMLInputElement>) => onUpdate((current) => ({ ...current, [field]: parseNumber(event.target.value, fallback) }));

  return (
    <section className="grid gap-5 text-sm text-[#1F2937]" data-testid="role-proactive-config">
      <div className="flex items-start justify-between gap-4"><div className="flex min-w-0 items-center gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-md bg-[#EFF6F4] text-[#2E7D5B]" aria-hidden="true"><PaperPlaneTilt className="h-5 w-5" weight="duotone" /></span><div><h2 className="text-sm font-semibold text-[#182230]">主动推送</h2><p className="mt-1 text-xs text-[#7B8794]">{roleForm.proactiveEnabled ? "角色会按设定的位置和策略主动投递。" : "启用后角色可在合适时机主动联系。"}</p></div></div><div className="flex shrink-0 items-center gap-3"><span className={roleForm.proactiveEnabled ? "text-xs text-[#2E7D5B]" : "text-xs text-[#7B8794]"}>{roleForm.proactiveEnabled ? "已启用" : "未启用"}</span><SettingsToggleCard checked={Boolean(roleForm.proactiveEnabled)} ariaLabel="主动推送" onChange={(checked) => onUpdate((current) => ({ ...current, proactiveEnabled: checked }))} /></div></div>
      <div className="grid gap-4 border-y border-[#E7ECF1] py-4 sm:grid-cols-2"><label className="grid gap-1.5 text-xs text-[#667085]"><span>首选投递位置</span><select className={roleDeliveryFieldClass} value={`${roleForm.proactiveTargetChannel ?? ""}:${roleForm.proactiveTargetChatId ?? ""}`} onChange={(event) => { const selected = bindings.find((binding) => `${binding.channel}:${binding.chat_id}` === event.target.value); onUpdate((current) => ({ ...current, proactiveTargetChannel: selected?.channel ?? "", proactiveTargetChatId: selected?.chat_id ?? "" })); }}><option value=":">未选择</option>{usableBindings.map((binding) => <option key={`${binding.channel}:${binding.chat_id}`} value={`${binding.channel}:${binding.chat_id}`}>{roleBindingChannelLabel(binding.channel)} · {binding.chat_id}</option>)}</select></label><label className="grid gap-1.5 text-xs text-[#667085]"><span>推送策略</span><select className={roleDeliveryFieldClass} value={roleForm.proactiveProfile ?? "daily"} onChange={(event) => onUpdate((current) => ({ ...current, proactiveProfile: event.target.value }))}><option value="daily">日常</option><option value="quiet">低打扰</option><option value="dev_verify">开发验证</option></select></label></div>
      {transportSequence.length ? <ol className="grid gap-2" data-testid="role-proactive-sequence">{transportSequence.map((binding, index) => <li className="flex min-w-0 items-center gap-3 border-b border-[#EEF2F5] py-2.5 last:border-b-0" key={`${binding.channel}:${binding.chat_id}`}><span className={index === 0 ? "grid h-6 w-6 shrink-0 place-items-center rounded-md bg-[#EFF6F4] text-xs font-medium text-[#2E7D5B]" : "grid h-6 w-6 shrink-0 place-items-center rounded-md bg-[#F3F6FA] text-xs text-[#667085]"}>{index + 1}</span><span className="min-w-0 truncate text-sm text-[#475467]">{roleBindingChannelLabel(binding.channel)} · {binding.chat_id}</span><span className="ml-auto shrink-0 text-xs text-[#7B8794]">{index === 0 ? "首选" : "无回复后尝试"}</span></li>)}</ol> : <p className="text-xs text-[#7B8794]">先在上方绑定渠道，再选择主动投递位置。</p>}
      <div><button className="flex items-center gap-1.5 rounded-md px-2.5 py-2 text-xs font-medium text-[#52606D] transition hover:bg-[#F3F6FA] hover:text-[#182230] focus:outline-none focus:ring-2 focus:ring-primary/20" type="button" aria-expanded={executionOpen} onClick={() => setExecutionOpen((current) => !current)}><SlidersHorizontal className="h-4 w-4" weight="bold" />执行参数<CaretDown className={executionOpen ? "h-4 w-4 rotate-180 transition-transform" : "h-4 w-4 transition-transform"} weight="bold" /></button>{executionOpen ? <div className="grid gap-4 border-t border-[#E7ECF1] pt-4"><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1.5 text-xs text-[#667085]"><span>Agent 模型</span><input className={roleDeliveryFieldClass} value={roleForm.proactiveAgentModel ?? ""} placeholder="沿用全局 Agent 模型" onChange={(event) => onUpdate((current) => ({ ...current, proactiveAgentModel: event.target.value }))} /></label><label className="grid gap-1.5 text-xs text-[#667085]"><span>Agent 最大步数</span><input className={roleDeliveryFieldClass} inputMode="numeric" value={String(roleForm.proactiveAgentMaxSteps ?? 35)} onChange={updateNumber("proactiveAgentMaxSteps", roleForm.proactiveAgentMaxSteps ?? 35)} /></label><label className="grid gap-1.5 text-xs text-[#667085]"><span>候选内容数</span><input className={roleDeliveryFieldClass} inputMode="numeric" value={String(roleForm.proactiveAgentContentLimit ?? 5)} onChange={updateNumber("proactiveAgentContentLimit", roleForm.proactiveAgentContentLimit ?? 5)} /></label><label className="grid gap-1.5 text-xs text-[#667085]"><span>网页上下文字符数</span><input className={roleDeliveryFieldClass} inputMode="numeric" value={String(roleForm.proactiveAgentWebFetchMaxChars ?? 8000)} onChange={updateNumber("proactiveAgentWebFetchMaxChars", roleForm.proactiveAgentWebFetchMaxChars ?? 8000)} /></label></div><div className="grid gap-4 border-t border-[#EEF2F5] pt-4"><div className="flex items-center justify-between gap-3"><div><h3 className="text-sm font-medium text-[#182230]">Drift</h3><p className="mt-1 text-xs text-[#7B8794]">控制角色对关系状态的主动漂移节奏。</p></div><SettingsToggleCard checked={Boolean(roleForm.proactiveDriftEnabled)} ariaLabel="Drift" onChange={(checked) => onUpdate((current) => ({ ...current, proactiveDriftEnabled: checked }))} /></div><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1.5 text-xs text-[#667085]"><span>Drift 最大步数</span><input className={roleDeliveryFieldClass} inputMode="numeric" value={String(roleForm.proactiveDriftMaxSteps ?? 20)} onChange={updateNumber("proactiveDriftMaxSteps", roleForm.proactiveDriftMaxSteps ?? 20)} /></label><label className="grid gap-1.5 text-xs text-[#667085]"><span>Drift 最小间隔（小时）</span><input className={roleDeliveryFieldClass} inputMode="numeric" value={String(roleForm.proactiveDriftMinIntervalHours ?? 3)} onChange={updateNumber("proactiveDriftMinIntervalHours", roleForm.proactiveDriftMinIntervalHours ?? 3)} /></label></div></div></div> : null}</div>
    </section>
  );
}
