"""Plugin-facing account group lifecycle; coordination remains host-owned."""

from typing import Protocol
from . import Channel


class AccountChannelGroup(Channel, Protocol):
    """A generation-owned collection of dynamically connected account channels."""

    def member(self, key: str) -> Channel | None: ...
    def member_channel(self, name: str) -> Channel | None: ...
    def member_channels(self) -> list[Channel]: ...
    async def add(self, key: str, channel: Channel) -> None: ...
    async def remove(self, key: str) -> Channel | None: ...
