import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";
import { resolve } from "node:path";
import { chromium, type Page } from "playwright";
import { configureSettingsConfigPath, loadSettingsData } from "../../src/settings";
import { fakeBridgeOfflineMessage, installOnboardingFakeBridge } from "./fakeBridge";

const url = process.env.SHIORI_QA_URL ?? "http://127.0.0.1:5187";
const output = resolve(".test-tmp-root/onboarding-qa");
await mkdir(output, { recursive: true });
configureSettingsConfigPath("qa.toml");
const initial = loadSettingsData("[llm]\n");
const browser = await chromium.launch({ executablePath: process.env.SHIORI_QA_BROWSER ?? "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe", headless: true });
const errors: string[] = [];
async function state(page: Page, patch: Record<string, unknown>) {
  await page.evaluate((patch) => {
    const value = JSON.parse(localStorage.getItem("qa.onboarding.bridge")!);
    localStorage.setItem("qa.onboarding.bridge", JSON.stringify({ ...value, ...patch }));
  }, patch);
  await page.reload();
}
async function heading(page: Page, name: string) { await page.getByRole("heading", { name, exact: true }).waitFor(); }
try {
  const context = await browser.newContext({ viewport: { width: 1320, height: 860 } });
  await context.addInitScript({ content: "globalThis.__name = (value) => value;" });
  await context.addInitScript(installOnboardingFakeBridge, initial);
  await context.route("**/qa-avatar.png", (route) => route.fulfill({ path: resolve("assets/shiori-app-icon.png"), contentType: "image/png" }));
  const page = await context.newPage();
  page.setDefaultTimeout(15_000);
  page.on("pageerror", (error) => { errors.push(error.message); console.error(error.stack ?? error.message); });
  await page.goto(url);
  await heading(page, "注册模型");
  await page.screenshot({ path: resolve(output, "model-desktop.png") });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: resolve(output, "model-mobile.png") });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.setViewportSize({ width: 1320, height: 860 });
  await page.getByRole("button", { name: "暂时跳过" }).click();
  await page.getByTestId("onboarding-page").waitFor({ state: "detached" });
  await page.reload();
  await page.locator(".app-frame").waitFor();
  await state(page, { sessionId: "launch-2" });
  await heading(page, "注册模型");
  await state(page, { offline: true });
  await page.getByRole("alert").filter({ hasText: fakeBridgeOfflineMessage }).waitFor();
  assert.equal(await page.getByRole("button", { name: "保存并继续" }).isEnabled(), false);
  await page.getByRole("button", { name: "模型注册设置" }).click();
  await page.getByRole("button", { name: "返回引导" }).click();
  await state(page, { offline: false, failSave: true });
  await heading(page, "注册模型");
  await page.getByRole("textbox", { name: "模型", exact: true }).fill("qa-model");
  await page.getByRole("button", { name: "测试连接" }).click();
  await page.getByRole("status").filter({ hasText: "连接成功" }).waitFor();
  await page.evaluate(() => window.dispatchEvent(new CustomEvent("qa:bridge", { detail: { connectionResult: { ok: false, message: "AuthenticationError: 401 Unauthorized" } } })));
  await page.getByRole("button", { name: "测试连接" }).click();
  await page.getByRole("status").filter({ hasText: "AuthenticationError: 401" }).waitFor();
  await page.getByRole("button", { name: "保存并继续" }).click();
  await page.getByRole("alert").filter({ hasText: "测试模型保存失败" }).waitFor();
  assert.equal(await page.getByRole("textbox", { name: "模型", exact: true }).inputValue(), "qa-model");
  await state(page, { failSave: false });
  await page.getByRole("textbox", { name: "模型", exact: true }).fill("qa-model");
  await page.getByRole("button", { name: "保存并继续" }).click();
  await heading(page, "创建角色");
  await state(page, { sessionId: "launch-3", failCreate: true });
  await heading(page, "创建角色");
  await page.getByRole("button", { name: "上传头像" }).click();
  await page.getByAltText("角色头像预览").waitFor();
  assert.ok(await page.getByAltText("角色头像预览").evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth > 0));
  await page.getByRole("button", { name: "移除头像" }).click();
  await page.getByRole("button", { name: "上传头像" }).click();
  await page.getByTestId("new-role-name").fill("小诗");
  await page.getByRole("textbox", { name: "角色设定", exact: true }).fill("安静、细心");
  await page.getByRole("button", { name: "创建角色", exact: true }).click();
  await page.getByRole("alert").filter({ hasText: "测试头像保存失败" }).waitFor();
  assert.equal(await page.getByTestId("new-role-name").inputValue(), "小诗");
  assert.equal(await page.getByAltText("角色头像预览").count(), 1);
  await page.screenshot({ path: resolve(output, "role-desktop.png") });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: resolve(output, "role-mobile.png"), fullPage: true });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await state(page, { failCreate: false, failReadsAfterCreate: true });
  await page.getByTestId("new-role-name").fill("小诗");
  await page.getByRole("textbox", { name: "角色设定", exact: true }).fill("安静、细心");
  await page.getByRole("button", { name: "上传头像" }).click();
  await page.getByRole("button", { name: "创建角色", exact: true }).click();
  await page.getByRole("alert").filter({ hasText: fakeBridgeOfflineMessage }).waitFor();
  await page.evaluate(() => window.dispatchEvent(new CustomEvent("qa:bridge", { detail: { offline: false } })));
  await page.getByRole("button", { name: "重试连接" }).click();
  await heading(page, "进入工作区");
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem("qa.onboarding.bridge")!).createCalls), 2);
  await page.screenshot({ path: resolve(output, "workspace-mobile.png") });
  await state(page, { sessionId: "launch-4" });
  await heading(page, "进入工作区");
  await page.setViewportSize({ width: 1320, height: 860 });
  await page.screenshot({ path: resolve(output, "workspace-desktop.png") });
  await page.getByRole("button", { name: "进入工作区", exact: true }).click();
  await page.getByTestId("onboarding-page").waitFor({ state: "detached" });
  await state(page, { sessionId: "launch-5", roles: [] });
  await page.locator(".app-frame").waitFor();
  assert.equal(await page.getByTestId("onboarding-page").count(), 0);
  // A pre-existing registration exempts a user who has never enrolled in onboarding.
  await page.evaluate(() => { localStorage.removeItem("onboarding.v1"); sessionStorage.clear(); });
  await page.reload();
  await page.locator(".app-frame").waitFor();
  assert.equal(await page.getByTestId("onboarding-page").count(), 0);
  assert.deepEqual(errors, []);
  // Every bridge method the renderer called has a real-shaped fake payload.
  assert.deepEqual(await page.evaluate(() => JSON.parse(localStorage.getItem("qa.onboarding.bridge")!).unknownMethods), []);
  console.log("PASS: first run, skip/reload/relaunch, bridge/settings failure, connection test, model save, role/avatar failure and recovery, completion/relaunch, responsive layout");
} finally { await browser.close(); }
