import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { app } from "electron";

const here = dirname(fileURLToPath(import.meta.url));

/** Absolute path to the built desktop package root. */
export const desktopRoot = resolve(here, "..");

const repositoryRoot = resolve(desktopRoot, "..", "..");

const packagedAssetsRoot = app.isPackaged && process.resourcesPath
  ? resolve(process.resourcesPath, "assets")
  : resolve(repositoryRoot, "assets");

/** Absolute path to the desktop shell icon asset used by Electron windows. */
export const desktopWindowIcon = resolve(
  packagedAssetsRoot,
  process.platform === "win32" ? "shiori-app-icon.ico" : "shiori-app-icon.png",
);

/** PNG artwork supported by Windows toast XML and the notification identity registry. */
export const desktopNotificationIcon = resolve(packagedAssetsRoot, "shiori-app-icon.png");

/** Absolute path to the icon used by Electron's native drag preview. */
export const desktopDragFileIcon = resolve(packagedAssetsRoot, "drag-file-icon.png");

/** Absolute path to the renderer HTML generated by Vite. */
export const rendererDist = resolve(desktopRoot, "renderer-dist", "index.html");

/**
 * Absolute path to the shared plugin-surface renderer entry generated by Vite.
 *
 * One entry serves every plugin-owned surface window; which plugin a given
 * window renders comes from its query string, not from a per-plugin HTML file.
 * See `src/surface/window.ts` for why that matters.
 */
export const rendererSurfaceDist = resolve(desktopRoot, "renderer-dist", "surface.html");

/** Absolute path to the hidden microphone capture renderer entry generated by Vite. */
export const rendererVoiceDist = resolve(desktopRoot, "renderer-dist", "voice.html");

/**
 * Absolute path to the hidden plugin-host renderer entry generated by Vite.
 *
 * One dedicated, never-shown window loads this and runs every plugin's
 * `app.background` contribution (#226 item 1) — see
 * `src/pluginHost/window.ts` for why that code cannot live in the main
 * window's renderer.
 */
export const rendererPluginHostDist = resolve(desktopRoot, "renderer-dist", "plugin-host.html");

/** Vite dev server URL used by the desktop shell during renderer development. */
export const rendererDevServerUrl = process.env.SHIORI_RENDERER_DEV_SERVER_URL;

/** Absolute path to the compiled preload script loaded by Electron. */
export const preloadScript = resolve(here, "preload.js");
