import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));

/** Absolute path to the built desktop package root. */
export const desktopRoot = resolve(here, "..");

/** Absolute path to the renderer HTML generated by Vite. */
export const rendererDist = resolve(desktopRoot, "renderer-dist", "index.html");

/** Absolute path to the compiled preload script loaded by Electron. */
export const preloadScript = resolve(here, "preload.js");
