import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));

/** Absolute path to the built desktop package root. */
export const desktopRoot = resolve(here, "..");

/** Absolute path to the desktop shell icon asset used by Electron windows. */
export const desktopWindowIcon = resolve(
  desktopRoot,
  "..",
  "assets",
  process.platform === "win32" ? "shiori-app-icon.ico" : "shiori-app-icon.png",
);

/** Absolute path to the renderer HTML generated by Vite. */
export const rendererDist = resolve(desktopRoot, "renderer-dist", "index.html");

/** Vite dev server URL used by the desktop shell during renderer development. */
export const rendererDevServerUrl = process.env.MIRA_RENDERER_DEV_SERVER_URL;

/** Absolute path to the compiled preload script loaded by Electron. */
export const preloadScript = resolve(here, "preload.js");
