"""Capability protocols consumed by role, generation and native-tool plugins."""

from collections.abc import Awaitable, Callable
from typing import Protocol
from .runtime import PluginRuntimeContext
from .extensions import ConfigValues, Dependencies, PrivateStorage, BackgroundTasks
from .http import HttpClient
from .models import ChatProvider, RoleModels
from .roles import Roles, SceneObservations
from .processes import Processes, Resources, ToolTurn
from .rpc import RpcCapability
from .tools import ToolsCapability
from .sessions import PluginSessions
from .tool_hooks import ToolHooksCapability
from .storage import KeyValueStore
from pathlib import Path


class RuntimeLifecycle(Protocol):
    """Retain accepted work until a replacing generation has drained it."""

    @property
    def was_active(self) -> bool: ...
    def on_drain(self, callback: Callable[[], Awaitable[None]]) -> None: ...


class ServicePluginContext(PluginRuntimeContext, Protocol):
    """Statically checked services; each property still requires a manifest grant."""

    @property
    def workspace(self) -> Path: ...
    @property
    def config(self) -> ConfigValues: ...
    @property
    def storage(self) -> PrivateStorage: ...
    @property
    def dependencies(self) -> Dependencies: ...
    @property
    def background(self) -> BackgroundTasks: ...
    @property
    def roles(self) -> Roles: ...
    @property
    def models(self) -> RoleModels: ...
    @property
    def sessions(self) -> PluginSessions: ...
    @property
    def tools(self) -> ToolsCapability: ...
    @property
    def kv(self) -> KeyValueStore: ...
    @property
    def rpc(self) -> RpcCapability: ...
    @property
    def http(self) -> HttpClient: ...
    @property
    def resources(self) -> Resources: ...
    @property
    def processes(self) -> Processes: ...
    @property
    def tool_turn(self) -> Callable[[], ToolTurn]: ...
    @property
    def runtime(self) -> RuntimeLifecycle: ...
    @property
    def scene_observations(self) -> SceneObservations: ...
    @property
    def tool_hooks(self) -> ToolHooksCapability: ...
    @property
    def light_provider(self) -> ChatProvider: ...
    @property
    def light_model(self) -> str: ...
